/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UASPaketB.View;


import javax.swing.JComboBox;
import UASPaketB.Controller.WarnetController;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class FormWarnet extends javax.swing.JFrame {

    /**
     * Creates new form FormWarnet
     */
    WarnetController controller;
    public FormWarnet() {
        initComponents();
        controller = new WarnetController (this);
        controller.setCboPelanggan();
        controller.setCboJenisPelanggan();
        controller.bersihForm();
        controller.tampilData();
    }

    public JComboBox<String> getCboPelanggan() {
        return cboPelanggan;
    }

    public JTextField getTxtKode() {
        return txtKode;
    }
    
    public JComboBox<String> getCboJenisPelanggan() {
        return cboJenisPelanggan;
    }
    
    public javax.swing.JTextField getTxtTanggalMasuk(){
        return txtTanggalMasuk;
    }
    
    public javax.swing.JTextField getTxtJamMasuk(){
        return txtJamMasuk;
    }
    
    public javax.swing.JTextField getTxtJamKeluar(){
        return txtJamKeluar;
    }
    
    public javax.swing.JTable getTblWarnet(){
        return tblWarnet;
    }

    public JTextField getTxtTarif() {
        return txtTarif;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtJamKeluar = new javax.swing.JTextField();
        txtTanggalMasuk = new javax.swing.JTextField();
        txtJamMasuk = new javax.swing.JTextField();
        cboJenisPelanggan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWarnet = new javax.swing.JTable();
        txtKode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboPelanggan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtTarif = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Warnet");
        getContentPane().setLayout(null);

        jLabel1.setText("Jam Keluar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 230, 78, 20);

        jLabel2.setText("Kode");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 30, 140, 20);

        jLabel3.setText("Jenis Pelanggan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 113, 20);

        jLabel4.setText("Tanggal Masuk");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 106, 20);

        jLabel5.setText("Jam Masuk");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 78, 20);

        txtJamKeluar.setText("jTextField1");
        getContentPane().add(txtJamKeluar);
        txtJamKeluar.setBounds(190, 230, 410, 26);

        txtTanggalMasuk.setText("jTextField1");
        getContentPane().add(txtTanggalMasuk);
        txtTanggalMasuk.setBounds(190, 150, 410, 26);

        txtJamMasuk.setText("jTextField1");
        getContentPane().add(txtJamMasuk);
        txtJamMasuk.setBounds(190, 190, 410, 26);

        cboJenisPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboJenisPelanggan);
        cboJenisPelanggan.setBounds(190, 110, 410, 26);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 320, 79, 30);

        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 320, 73, 29);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 320, 83, 29);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 320, 77, 29);

        tblWarnet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Pelanggan", "Jenis Pelanggan", "Tanggal Masuk", "Jam Masuk", "Jam Keluar", "Lama", "Tarif", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWarnet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWarnetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblWarnet);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 370, 850, 360);

        txtKode.setText("jTextField1");
        getContentPane().add(txtKode);
        txtKode.setBounds(190, 30, 410, 26);

        jLabel6.setText("Pelanggan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 70, 73, 20);

        cboPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboPelanggan);
        cboPelanggan.setBounds(190, 70, 410, 26);

        jLabel7.setText("Tarif");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 270, 51, 20);

        txtTarif.setText("jTextField1");
        getContentPane().add(txtTarif);
        txtTarif.setBounds(190, 270, 410, 26);

        setSize(new java.awt.Dimension(903, 715));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        controller.saveWarnet();
        controller.tampilData();
        controller.bersihForm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        controller.UpdateWarnet();
        controller.tampilData();
        controller.bersihForm();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controller.bersihForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        controller.deleteWarnet();
        controller.tampilData();
        controller.bersihForm();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblWarnetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWarnetMouseClicked
        // TODO add your handling code here:
        controller.getWarnet();
    }//GEN-LAST:event_tblWarnetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormWarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormWarnet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboJenisPelanggan;
    private javax.swing.JComboBox<String> cboPelanggan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWarnet;
    private javax.swing.JTextField txtJamKeluar;
    private javax.swing.JTextField txtJamMasuk;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtTanggalMasuk;
    private javax.swing.JTextField txtTarif;
    // End of variables declaration//GEN-END:variables
}
